terraform {
  required_providers {
    oci = {
      source  = "oracle/oci"
      version = "~> 5.0"
    }
  }
}

provider "oci" {
  # This tells Terraform to use the credentials generated by your OCI CLI setup
  # typically located at ~/.oci/config
  config_file_profile = "DEFAULT"
}